### ISSUE TITLE
Jacqueline's git repo

### ISSUE THREAD

**Issue by Wolflab** [pearselab/r-intro-Wolflab#3]
Will: There are probably several ways to get Jacqueline's repo working so you can see it. How do you want it worked on this end? Shall we just clone to the correct repo in your class?

Please advise.

Thanks

Paul

**Comment by willpearse** [comment]
I can see it (I've already told her this!). Tell her to just carry on as she is. Also, feel free to "scald" her for not coming to office hours etc. despite not understanding what was going on...

**Comment by Wolflab** [comment]
Will: I have now helped several folks who were having "problems" with git not seeing a changed file to commit. In all cases, they had been editing a copy of the file that was not in the git dir. As soon as they moved the edited file into the git dir, all worked. So git was behaving, but the damn "save as" in an application was probably causing the problem.  Maybe. SO far so good. This class is going much better.

**Comment by willpearse** [comment]
Ha! You're doing amazing triage work not Paul - thank you!...

**Comment by Wolflab** [comment]
OK - so we just need to do the usual add, commit, push

Paul
