### ISSUE TITLE
General Course feedback

### ISSUE THREAD

**Issue by Wolflab** [pearselab/r-intro-Wolflab#5]
Will: You have a lecture listed for November 23. That day is a holiday (thanksgiving), so no lectures - campus is closed. I am not sure if you regard that good or bad news. Also, I will not be here Nov 21. Ditto good or bad news.

Are you going to post due dates for these other exercises? I see R intro due Nov 4, but not these other exercises. Or is there a difference between an exercise (ungraded?) and homework (graded?)

**Comment by willpearse** [comment]
I'm not sure what I'll do about those days yet; I guess I'll have to extend the class to run later. That could cause trouble, but I'll figure that out tomorrow (i.e., once I've dealt with today :D)

I'll go through the deadlines for the homework and exercises again in class. If you could get some kind of feedback, informally, about whether those are actually feasible for the students I would be grateful. I haven't seen anyone who's finished the second set of exercises up on GitHub, and that's giving me some cause for concern. I don't mind if not everyone gets an A, but if no one finishes the exercises I should perhaps give everyone more time etc.

**Comment by Wolflab** [comment]
Carol and I are at Q13. But it took most of the weekend and Tuesday. I think there are several students who are slower than me - certainly some who are faster. But I am learning lots. Although Q12 had me at a road block for most of the day - it has opened up some very useful skills now. I think you are going to see some very high variance of ability and time to completion. I'll see if I can make a simulation of this.....

**Comment by willpearse** [comment]
If you can simulate people coding, you might just have solved a few high-level problems in programming...

Right, makes sense. I'm going to look into moving the schedule around and then I'll get back to you.

**Comment by Wolflab** [comment]
Following I sent in a a direct email so just pasting here for records:
I am not sure that extending the work time for exercises will help much (but need to think about that).  A possible effect of that is a major accumulation of work all at the end (combined with the same for Zach’s Bayesian class, which is also killing them. {I am getting seriously concerned that I have three great new students who are taking both these courses first semester of grad school – I hope they don’t drop out!}.

Idea: and I hope this doesn’t get us both hung, drawn, and quartered. These exercises are long. Extending the due date extends the time until they get feedback. Not good because so much of what you do and students do is building on earlier stuff. Solution seems to break the exercises up into smaller sections with MORE due dates, and earlier due dates.  For example the current exercise, have Q 1-10 due next week?

**Comment by Wolflab** [comment]
I will try to get some feedback from students. They are generally not too shy about this sort of stuff.

**Comment by willpearse** [comment]
I'm not such a fan of breaking them up, but would potentially be up for cutting off some of the later questions entirely. So, for example, I could get rid of a huge hunk of session four, since that's more advanced and is really just practice of the concepts in the rest of the class.

I suggest this because, otherwise, I think people are going to panic when I say "session two is due at the end of the week" when they could, in theory, have been planning their time all along. This way they still have loads of time, and I'm not getting myself into a situation where a conscientious student who's kept up with the work is made to feel like that effort was wasted. Does that make sense?

**Comment by Wolflab** [comment]
I see. Agree. Perhaps a nudge today to move along? In the context of push to repo often. Not that you haven't been saying this all along

The only solution is to get an extra ten hours per day. One extra day per week would also be helpful. Too much to learn. Too little time

P

Sent from my iPhone

On Oct 26, 2016, at 8:37 AM, Will Pearse <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not such a fan of breaking them up, but would potentially be up for cutting off some of the later questions entirely. So, for example, I could get rid of a huge hunk of session four, since that's more advanced and is really just practice of the concepts in the rest of the class.

I suggest this because, otherwise, I think people are going to panic when I say "session two is due at the end of the week" when they could, in theory, have been planning their time all along. This way they still have loads of time, and I'm not getting myself into a situation where a conscientious student who's kept up with the work is made to feel like that effort was wasted. Does that make sense?

##

**Comment by Wolflab** [comment]
Performance programming: 

Not sure if everyone (or anyone) would agree. But I find performance programming incredibly helpful. And ESPECIALLY when teacher screws up and has to correct errors. Much of the time that is what we do, so watching how an expert spots a problem and then fixes it is really useful for students to see. So please continue to program on the fly, but when something goes wrong, work through the corrections slowly, OR ask if a student here can spot (and correct) the "deliberate" error.

**Comment by willpearse** [comment]
Thanks - I realise I replied to the performance comment in the wrong thread (oh no!...)

I pushed the repo angle (ha ha!) today a bit. Let's see how they do today, and dependent on that I might cut some of the stuff from session 4.

**Comment by willpearse** [comment]
I will make a push for them to put everything up today at the end of the session (they're meant to be giving me things for me to check on Friday anyway)

**Comment by Wolflab** [comment]
I hear you chatting with Bodie. I suspect that he will end up being better than some of the grad students. He might actually have more background in many of the areas. This reminds me, if you notice (via github) that some students might need more one-on-one help, please let me know. I can try to help directly from this end.

**Comment by willpearse** [comment]
Great, thanks Paul. He does seem to have his head screwed on well!...

I will let you know. I'm going to review everyone tomorrow morning and I'll send you an email about it.
