### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by Wolflab** [pearselab/r-intro-Wolflab#8]
@marleyhaupt1

Marley: can you read this?

**Comment by marleyhaupt1** [comment]
Yep sure can 👍

**Comment by Wolflab** [comment]
Hey Marley: I looked at your Gompertz code. Very similar to mine (fewer parentheses - I think I was being paranoid). I tested both with the same arguments and got the same answers. I think you kept getting the same number because you picked a late level of time and fast pop growth rate (c) which results in reaching asymptote quickly (before "time"). Try these values:
print(gompertz(4, 20, 33, 1))

Your code is good.

**Comment by Wolflab** [comment]
Or, it is bad and we both made the same mistakes :)

**Comment by marleyhaupt1** [comment]
Ha ha thanks Paul! You're awesome.

**Comment by Wolflab** [comment]
Always good to do some testing. And always good to make sure the tests are good tests. I think we will get more on this later in the course!

**Comment by willpearse** [comment]
That you will. Unit tests are great, although they do have their down-sides too...
